### ISSUE TITLE
No Levanta Iframe para Catastro de Tarjeta

### ISSUE THREAD

**Issue by martinpa13py** [marioungui/woocommerce-bancard#1]
Buenas, he estado intentando usar el plugin en un woocomerce, de lo cual observo que el mismo no levanta el iFrame para el registro de tarjetas, obsservo en el backend el siguiente error 

![image](https://github.com/user-attachments/assets/f2d96266-f9ff-4c70-880c-d07051c1f18e)

y en el frontend el siguiente error

![image](https://github.com/user-attachments/assets/d8b153d5-a20d-4977-9234-89c8866a829a)

El Sitio tiene la siguiente configuracion

![image](https://github.com/user-attachments/assets/8618bb11-fb5a-430d-9118-f35c3dddcbdc)

Podria estar realizando algun paso mal ?

Desde ya muchas gracias

**Comment by marioungui** [comment]
Hola @martinpa13py

Al parecer el plugin que estás usando **no corresponde a este repositorio**. Ya que este plugin por ejemplo setea automáticamente varios de los campos (como URL's y entorno) tanto a través de variables globales de woocommerce como registrando llamadas a través de `WC_API`

Al parecer estás usando el plugin oficial de Bancard.

De igual manera, pareciera ser que el problema que estás teniendo es que estás ejecutando en `localhost` y por tanto Bancard no puede ver el entorno de desarrollo. Por tanto te sugeriría que puedas pasar a un ambiente DEV accesible a través de internet y/o crear un túnel público a tu host.

Marco esto como cerrado ya que el plugin no corresponde a este repositorio.

**Comment by martinpa13py** [comment]
Comprendido. Muchas Gracias !
